publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://www.kcplt.cn/"
canonifyurls = true
theme = "hugo-academic-group"
title = "KCP lab"
math = true
copyright = "&copy; Wentao Lyu, 2023 "

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of research group"
  author = "Your name"
  email = "mail@example.org"
  address = "3566 Spirit Drive NEW HAVEN Connecticut"

  slogan = "Laboratory of KCP （Digital Image Processing）"
  slogan_text = "we believe that with knowledge, courage, and perseverance (KCP), somethings can be achieved."

  [params.logo]
  image = "img/logo.jpg"
  link = "https://www.zstu.edu.cn"

  [[params.navbar_hierarchy]]
  name ="KCP Lab"
  link = "/"
  position = 1

  [[params.slogan_columns]]
    title1 = "Wentao LYU 吕文涛"
    text1 = "* Associate Professor"
    text2 = "* Office: Building No.25, Room 1013-1015"
    text3 = "* Tel: +86-571-86843325"
    text4 = "* Email: alvinlwt@zstu.edu.cn"
    weight = 1


  [[params.slogan_columns]]
    title1 = "Brief Biography"
    text1 = "1. Wentao Lyu received Ph.D. from Shanghai Jiao Tong University in 2015. Associate Professor of School of ISE, Zhejiang Sci-Tech University, Master Supervisor. From 2018.9-2019.9, as a Visiting scholar at the Department of ECE, University of Waterloo, Canada."
    text2 = "2. Academic works include machine learning, image processing and network optimization. Has published more than 60 SCI/EI journal and conference papers, approved and applied for more than 40 patents."
    text3 = "3. Engineering works include AI and related digital technologies for Industrial scenarios; technical solutions and support for industrial intelligent transformation; and industrial IOT systems, MES and ERP..."
    link_text = "Address: room 1013, building #25, Zhejiang Sci-Tech University (@ XiaSha) Hangzhou, China."
    mail = "alvinlwt@zstu.edu.cn"
    weight = 1


  [[params.slogan_columns]]
    title1 = "Updates"
    text1 = "[Next topic] Industrial defect detection based on anchor-free detectors and knowledge distillation, May 19/2023, reported by Z. Liu."
    text2 = "W. Lyu, A novel discriminative dictionary learning method for image classification, to appear in IEICE Trans. Fund., Jun. 2023."
    text3 = "Y. Chen, SBL model based on LHP and GAMP for image reconstruction, submitted to IEEE Signal Process. Lett., Febr. 2023."
    text4 = "[Congratulations!] Progressive pyramid network for defect dection, written by Y. Xu, has been published online in Knowledge-based systems, May 2023."
    text5 = "Y. Zheng, Efficient conflict network for defect detection, submitted to IEEE Trans. Instrum. Measur., Mar. 2023."
    weight = 1
  


  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"

  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]]
      name = "Research"
      url = "/research"
      weight = 2

  [[menu.main]]
      name = "Publications"
      url = "/publication/"
      weight = 3


  [[menu.main]]
      name = "Members"
      url = "/member/"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "/post/"
      weight = 6


  [[menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 7
