publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://www.kcplt.cn/"
canonifyurls = true
theme = "hugo-academic-group"
title = "KCP lab"
math = true
copyright = "&copy; Wentao Lyu, 2023 "

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of research group"
  author = "Your name"
  email = "mail@example.org"
  address = "3566 Spirit Drive NEW HAVEN Connecticut"

  slogan = "Laboratory of KCP （Image Processing）"
  slogan_text = "School of Information Science and Engineering, Zhejiang Sci-Tech University"

  [params.logo]
  image = "img/logo.jpg"
  link = "https://www.zstu.edu.cn"

  [[params.navbar_hierarchy]]
  name ="KCP Lab"
  link = "/"
  position = 1

  [[params.slogan_columns]]
    title1 = "Belief"
    text1 = "1. We believe that with"
    text2 = "2. Knowledge, Courage, and Perseverance (KCP)"
    text3 = "3. somethings can be ACHIEVED"
    weight = 1


  [[params.slogan_columns]]
    title1 = "Introduction"
    text1 = "1. Wentao Lyu, Ph.D. from Shanghai Jiao Tong University, Associate Professor of School of Information, Zhejiang Sci-tech University, Master Supervisor. From 2018.9-2019.9, as a Visiting scholar at the Department of Electrical and Computer Engineering, University of Waterloo, Canada."
    text2 = "2. Research interests include machine learning, intelligent image processing and network optimization. Has published more than 40 SCI/EI journals, approved and applied for more than 30 patents."
    text3 = "3. Focus on theoretical research and engineering application in artificial intelligence, digital technology and other related fields. Participate in the intelligent transformation for industrial enterprises, including design, production, management and service; Develop industrial IOT systems, MES and ERP, just name a few."
    link_text = "Address: room 1013, building #25, Zhejiang Sci-Tech University (@ XiaSha)"
    mail = "alvinlwt@zstu.edu.cn"
    weight = 1


  [[params.slogan_columns]]
    title1 = "Updates"
    text1 = "1. Next topic: KSVD-Based sparse representation model for image denoising, reported by P. Chen."
    text2 = "2. Y. Chen, SBL model based on LHP and GAMP for image reconstruction, submitted to IEEE Signal Processing Letters."
    text3 = "3. Y. Zheng, Efficient confilict network for defect dection, sumbitted to IEEE Transactions on Instrumentation and Measurement."
    text4 = "4. K. Yu, Fa-yolo network design for fabric defect dection, sumbitted to IEIEE Transactions on Fundamentals."
    weight = 1


  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"

  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]]
      name = "Research"
      url = "/research"
      weight = 2

  [[menu.main]]
      name = "Publications"
      url = "/publication/"
      weight = 3


  [[menu.main]]
      name = "Members"
      url = "/member/"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "/post/"
      weight = 6


  [[menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 7
